"""
core/sector_map.py

Real sector/theme mapping. Started as a ~60-stock hand-curated set
adapted from Alpha1/nse_universe.py, expanded using NSE's own
official sectoral index constituent lists (expand_sector_map.py).

Coverage as of last expansion: 212 stocks.
Any ticker not in this mapping still falls back to UNKNOWN - the
sector cap only protects candidates within this mapping, not a
comprehensive guarantee across the whole universe.
"""

UNIVERSE = {
    "ABB.NS": {"sector": "Energy", "theme": "Energy"},
    "ABBOTINDIA.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "ABREL.NS": {"sector": "Realty", "theme": "Realty"},
    "ADANIENSOL.NS": {"sector": "Energy", "theme": "Energy"},
    "ADANIENT.NS": {"sector": "Metal", "theme": "Metal"},
    "ADANIGREEN.NS": {"sector": "Energy Transition", "theme": "Green Energy"},
    "ADANIPORTS.NS": {"sector": "Logistics", "theme": "Ports"},
    "ADANIPOWER.NS": {"sector": "Energy", "theme": "Power Generation"},
    "AEGISLOG.NS": {"sector": "Oil & Gas", "theme": "Oil & Gas"},
    "AEGISVOPAK.NS": {"sector": "Oil & Gas", "theme": "Oil & Gas"},
    "AJANTPHARM.NS": {"sector": "Pharma", "theme": "Pharma"},
    "ALKEM.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "AMBER.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "ANANTRAJ.NS": {"sector": "Realty", "theme": "Realty"},
    "APLAPOLLO.NS": {"sector": "Metal", "theme": "Metal"},
    "APOLLOHOSP.NS": {"sector": "Healthcare", "theme": "Hospitals"},
    "ASHOKLEY.NS": {"sector": "Auto", "theme": "Auto"},
    "ASIANPAINT.NS": {"sector": "Consumer", "theme": "Paints"},
    "ATGL.NS": {"sector": "Oil & Gas", "theme": "Oil & Gas"},
    "AUBANK.NS": {"sector": "Banking", "theme": "Banking"},
    "AUROPHARMA.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "AXISBANK.NS": {"sector": "Banking", "theme": "Private Banking"},
    "BAJAJ-AUTO.NS": {"sector": "Auto", "theme": "Auto"},
    "BAJAJFINSV.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "BAJFINANCE.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "BANKBARODA.NS": {"sector": "Banking", "theme": "PSU Banking"},
    "BANKINDIA.NS": {"sector": "PSU Bank", "theme": "PSU Bank"},
    "BATAINDIA.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "BDL.NS": {"sector": "Defence", "theme": "Missile Systems"},
    "BEL.NS": {"sector": "Defence", "theme": "Electronics Defence"},
    "BHARATFORG.NS": {"sector": "Auto", "theme": "Auto"},
    "BHEL.NS": {"sector": "Energy", "theme": "Energy"},
    "BIOCON.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "BLUESTARCO.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "BOSCHLTD.NS": {"sector": "Auto", "theme": "Auto"},
    "BPCL.NS": {"sector": "Energy", "theme": "Oil PSU"},
    "BRIGADE.NS": {"sector": "Realty", "theme": "Realty"},
    "BRITANNIA.NS": {"sector": "FMCG", "theme": "FMCG"},
    "BSE.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "CANBK.NS": {"sector": "PSU Bank", "theme": "PSU Bank"},
    "CASTROLIND.NS": {"sector": "Oil & Gas", "theme": "Oil & Gas"},
    "CENTRALBK.NS": {"sector": "PSU Bank", "theme": "PSU Bank"},
    "CESC.NS": {"sector": "Energy", "theme": "Energy"},
    "CGPOWER.NS": {"sector": "Energy", "theme": "Energy"},
    "CHENNPETRO.NS": {"sector": "Oil & Gas", "theme": "Oil & Gas"},
    "CHOLAFIN.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "CIPLA.NS": {"sector": "Healthcare", "theme": "Pharma"},
    "COALINDIA.NS": {"sector": "Energy", "theme": "Energy"},
    "COCHINSHIP.NS": {"sector": "Defence", "theme": "Shipbuilding"},
    "COFORGE.NS": {"sector": "IT", "theme": "IT"},
    "COLPAL.NS": {"sector": "FMCG", "theme": "FMCG"},
    "CONCOR.NS": {"sector": "Logistics", "theme": "Rail Freight"},
    "CROMPTON.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "DABUR.NS": {"sector": "FMCG", "theme": "FMCG"},
    "DBCORP.NS": {"sector": "Media", "theme": "Media"},
    "DELHIVERY.NS": {"sector": "Logistics", "theme": "E-commerce Logistics"},
    "DIVISLAB.NS": {"sector": "Healthcare", "theme": "API Pharma"},
    "DIXON.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "DLF.NS": {"sector": "Realty", "theme": "Realty"},
    "DMART.NS": {"sector": "Consumer", "theme": "Retail"},
    "DRREDDY.NS": {"sector": "Healthcare", "theme": "Pharma"},
    "EICHERMOT.NS": {"sector": "Auto", "theme": "Auto"},
    "EMAMILTD.NS": {"sector": "FMCG", "theme": "FMCG"},
    "ENRIN.NS": {"sector": "Energy", "theme": "Energy"},
    "EXIDEIND.NS": {"sector": "Auto", "theme": "Auto"},
    "FEDERALBNK.NS": {"sector": "Banking", "theme": "Banking"},
    "FORTIS.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "GAIL.NS": {"sector": "Energy", "theme": "Gas Utility"},
    "GATI.NS": {"sector": "Logistics", "theme": "Express Logistics"},
    "GLAND.NS": {"sector": "Pharma", "theme": "Pharma"},
    "GLENMARK.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "GODREJCP.NS": {"sector": "FMCG", "theme": "FMCG"},
    "GODREJPROP.NS": {"sector": "Realty", "theme": "Realty"},
    "GRSE.NS": {"sector": "Defence", "theme": "Naval Defence"},
    "GVT&D.NS": {"sector": "Energy", "theme": "Energy"},
    "HAL.NS": {"sector": "Defence", "theme": "Aerospace & Defence"},
    "HATHWAY.NS": {"sector": "Media", "theme": "Media"},
    "HAVELLS.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "HCLTECH.NS": {"sector": "IT", "theme": "Enterprise IT"},
    "HDFCBANK.NS": {"sector": "Banking", "theme": "Private Banking"},
    "HDFCLIFE.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "HEROMOTOCO.NS": {"sector": "Auto", "theme": "Auto"},
    "HINDALCO.NS": {"sector": "Metal", "theme": "Metal"},
    "HINDCOPPER.NS": {"sector": "Metal", "theme": "Metal"},
    "HINDPETRO.NS": {"sector": "Oil & Gas", "theme": "Oil & Gas"},
    "HINDUNILVR.NS": {"sector": "Consumer", "theme": "FMCG"},
    "HINDZINC.NS": {"sector": "Metal", "theme": "Metal"},
    "HPCL.NS": {"sector": "Energy", "theme": "Oil PSU"},
    "ICICIBANK.NS": {"sector": "Banking", "theme": "Private Banking"},
    "ICICIGI.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "IDFCFIRSTB.NS": {"sector": "Banking", "theme": "Banking"},
    "IGL.NS": {"sector": "Oil & Gas", "theme": "Oil & Gas"},
    "INDIANB.NS": {"sector": "PSU Bank", "theme": "PSU Bank"},
    "INDUSINDBK.NS": {"sector": "Banking", "theme": "Mid Private Bank"},
    "INFY.NS": {"sector": "IT", "theme": "Cloud + AI"},
    "INOXWIND.NS": {"sector": "Energy Transition", "theme": "Wind Infra"},
    "IOB.NS": {"sector": "PSU Bank", "theme": "PSU Bank"},
    "IOC.NS": {"sector": "Energy", "theme": "Oil PSU"},
    "IPCALAB.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "IRCON.NS": {"sector": "Infrastructure", "theme": "Rail EPC"},
    "IRFC.NS": {"sector": "Infrastructure", "theme": "Rail Financing"},
    "ITC.NS": {"sector": "Consumer", "theme": "FMCG + Cigarettes"},
    "JINDALSTEL.NS": {"sector": "Metal", "theme": "Metal"},
    "JIOFIN.NS": {"sector": "FinTech", "theme": "Financial Services"},
    "JPPOWER.NS": {"sector": "Energy", "theme": "Energy"},
    "JSL.NS": {"sector": "Metal", "theme": "Metal"},
    "JSWENERGY.NS": {"sector": "Energy", "theme": "Energy"},
    "JSWSTEEL.NS": {"sector": "Metal", "theme": "Metal"},
    "KAJARIACER.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "KALYANKJIL.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "KOTAKBANK.NS": {"sector": "Banking", "theme": "Private Banking"},
    "LAURUSLABS.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "LGEINDIA.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "LICHSGFIN.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "LLOYDSME.NS": {"sector": "Metal", "theme": "Metal"},
    "LODHA.NS": {"sector": "Realty", "theme": "Realty"},
    "LT.NS": {"sector": "Infrastructure", "theme": "Infra + EPC"},
    "LTIM.NS": {"sector": "IT", "theme": "Digital Transformation"},
    "LTM.NS": {"sector": "IT", "theme": "IT"},
    "LUPIN.NS": {"sector": "Healthcare", "theme": "Pharma"},
    "M&M.NS": {"sector": "Auto", "theme": "Auto"},
    "MAHABANK.NS": {"sector": "PSU Bank", "theme": "PSU Bank"},
    "MANKIND.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "MARICO.NS": {"sector": "FMCG", "theme": "FMCG"},
    "MARUTI.NS": {"sector": "Auto", "theme": "Auto"},
    "MAXHEALTH.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "MAZDOCK.NS": {"sector": "Defence", "theme": "Naval Shipbuilding"},
    "MFSL.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "MGL.NS": {"sector": "Oil & Gas", "theme": "Oil & Gas"},
    "MOTHERSON.NS": {"sector": "Auto", "theme": "Auto"},
    "MPHASIS.NS": {"sector": "IT", "theme": "IT"},
    "MUTHOOTFIN.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "NATIONALUM.NS": {"sector": "Metal", "theme": "Metal"},
    "NAVA.NS": {"sector": "Energy", "theme": "Energy"},
    "NAZARA.NS": {"sector": "Media", "theme": "Media"},
    "NBCC.NS": {"sector": "Infrastructure", "theme": "Govt Infra"},
    "NESTLEIND.NS": {"sector": "Consumer", "theme": "FMCG"},
    "NETWORK18.NS": {"sector": "Media", "theme": "Media"},
    "NHPC.NS": {"sector": "Energy", "theme": "Energy"},
    "NLCINDIA.NS": {"sector": "Energy", "theme": "Coal Power"},
    "NMDC.NS": {"sector": "Metal", "theme": "Metal"},
    "NTPC.NS": {"sector": "Energy", "theme": "Power Generation"},
    "NTPCGREEN.NS": {"sector": "Energy", "theme": "Energy"},
    "OBEROIRLTY.NS": {"sector": "Realty", "theme": "Realty"},
    "OFSS.NS": {"sector": "IT", "theme": "IT"},
    "OIL.NS": {"sector": "Oil & Gas", "theme": "Oil & Gas"},
    "ONGC.NS": {"sector": "Energy", "theme": "Oil PSU"},
    "PATANJALI.NS": {"sector": "FMCG", "theme": "FMCG"},
    "PAYTM.NS": {"sector": "FinTech", "theme": "Digital Payments"},
    "PERSISTENT.NS": {"sector": "IT", "theme": "AI Engineering"},
    "PETRONET.NS": {"sector": "Energy", "theme": "LNG Infra"},
    "PFC.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "PFOCUS.NS": {"sector": "Media", "theme": "Media"},
    "PGEL.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "PHOENIXLTD.NS": {"sector": "Realty", "theme": "Realty"},
    "PNB.NS": {"sector": "Banking", "theme": "PSU Banking"},
    "PNCINFRA.NS": {"sector": "Infrastructure", "theme": "Road EPC"},
    "POLICYBZR.NS": {"sector": "FinTech", "theme": "Insurance Tech"},
    "POWERGRID.NS": {"sector": "Energy", "theme": "Power Transmission"},
    "POWERINDIA.NS": {"sector": "Energy", "theme": "Energy"},
    "PPLPHARMA.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "PRESTIGE.NS": {"sector": "Realty", "theme": "Realty"},
    "PSB.NS": {"sector": "PSU Bank", "theme": "PSU Bank"},
    "PVRINOX.NS": {"sector": "Media", "theme": "Media"},
    "RADICO.NS": {"sector": "FMCG", "theme": "FMCG"},
    "RECLTD.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "RELIANCE.NS": {"sector": "Energy", "theme": "Energy + Digital Infra"},
    "RPOWER.NS": {"sector": "Energy", "theme": "Energy"},
    "RVNL.NS": {"sector": "Infrastructure", "theme": "Rail Infra"},
    "SAIL.NS": {"sector": "Metal", "theme": "Metal"},
    "SAILIFE.NS": {"sector": "Pharma", "theme": "Pharma"},
    "SAREGAMA.NS": {"sector": "Media", "theme": "Media"},
    "SBICARD.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "SBILIFE.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "SBIN.NS": {"sector": "Banking", "theme": "PSU Banking"},
    "SHRIRAMFIN.NS": {"sector": "Financial Services", "theme": "Financial Services"},
    "SIEMENS.NS": {"sector": "Energy", "theme": "Energy"},
    "SJVN.NS": {"sector": "Energy", "theme": "Energy"},
    "SOBHA.NS": {"sector": "Realty", "theme": "Realty"},
    "SONACOMS.NS": {"sector": "Auto", "theme": "Auto"},
    "SUNPHARMA.NS": {"sector": "Healthcare", "theme": "Pharma"},
    "SUNTV.NS": {"sector": "Media", "theme": "Media"},
    "SUZLON.NS": {"sector": "Energy Transition", "theme": "Wind Energy"},
    "SYNGENE.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "TATACONSUM.NS": {"sector": "FMCG", "theme": "FMCG"},
    "TATAPOWER.NS": {"sector": "Energy", "theme": "Renewable + Utility"},
    "TATASTEEL.NS": {"sector": "Metal", "theme": "Metal"},
    "TCS.NS": {"sector": "IT", "theme": "AI Services"},
    "TECHM.NS": {"sector": "IT", "theme": "Telecom + IT"},
    "THERMAX.NS": {"sector": "Energy", "theme": "Energy"},
    "TIINDIA.NS": {"sector": "Auto", "theme": "Auto"},
    "TIPSMUSIC.NS": {"sector": "Media", "theme": "Media"},
    "TITAN.NS": {"sector": "Consumer", "theme": "Jewellery"},
    "TMPV.NS": {"sector": "Auto", "theme": "Auto"},
    "TORNTPHARM.NS": {"sector": "Healthcare", "theme": "Healthcare"},
    "TORNTPOWER.NS": {"sector": "Energy", "theme": "Energy"},
    "TVSMOTOR.NS": {"sector": "Auto", "theme": "Auto"},
    "UBL.NS": {"sector": "FMCG", "theme": "FMCG"},
    "UCOBANK.NS": {"sector": "PSU Bank", "theme": "PSU Bank"},
    "UNIONBANK.NS": {"sector": "PSU Bank", "theme": "PSU Bank"},
    "UNITDSPR.NS": {"sector": "FMCG", "theme": "FMCG"},
    "UNOMINDA.NS": {"sector": "Auto", "theme": "Auto"},
    "VBL.NS": {"sector": "FMCG", "theme": "FMCG"},
    "VEDL.NS": {"sector": "Metal", "theme": "Metal"},
    "VOLTAS.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "WELCORP.NS": {"sector": "Metal", "theme": "Metal"},
    "WHIRLPOOL.NS": {"sector": "Consumer Durables", "theme": "Consumer Durables"},
    "WIPRO.NS": {"sector": "IT", "theme": "IT Services"},
    "WOCKPHARMA.NS": {"sector": "Pharma", "theme": "Pharma"},
    "YESBANK.NS": {"sector": "Banking", "theme": "Banking"},
    "ZEEL.NS": {"sector": "Media", "theme": "Media"},
    "ZYDUSLIFE.NS": {"sector": "Healthcare", "theme": "Healthcare"},
}


def get_sector(ticker):
    """Returns the real sector for a ticker if we have it curated,
    otherwise UNKNOWN - callers should treat UNKNOWN as "don't apply
    the sector cap to this one, we genuinely don't know."""

    clean = ticker.upper().strip()
    if not clean.endswith(".NS"):
        clean += ".NS"

    entry = UNIVERSE.get(clean)
    return entry["sector"] if entry else "UNKNOWN"