from enum import Enum

class PipelineState(Enum):
    CREATED = "CREATED"
    RESEARCH_DONE = "RESEARCH_DONE"
    OPTIMIZED = "OPTIMIZED"
    RISK_CHECKED = "RISK_CHECKED"
    GOVERNANCE_CLEARED = "GOVERNANCE_CLEARED"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"
