# portfolio/optimization/contracts/optimization_contract.py
import dataclasses
from datetime import datetime
from decimal import Decimal
from typing import Tuple
from portfolio.contracts.portfolio_certificate import TargetWeight
from research.governance.serialization import CanonicalSerializer

@dataclasses.dataclass(frozen=True)
class OptimizationRequest:
    """
    The immutable payload dispatched to the Deterministic Optimizer.
    Contains cryptographic pointers, objective identifiers, sizing, 
    and the execution environment hash.
    """
    universe_certificate_hash: str
    risk_snapshot_hash: str
    constraint_set_hash: str
    objective_id: str
    portfolio_aum: Decimal
    timestamp: datetime
    numerical_environment_hash: str  # Binds the runtime matrix math environment

    @property
    def request_hash(self) -> str:
        return CanonicalSerializer.hash(self)

@dataclasses.dataclass(frozen=True)
class OptimizationResult:
    """
    The raw numerical proposal generated by the solver.
    Carries zero certification authority.
    """
    request_hash: str
    target_weights: Tuple[TargetWeight, ...]
    objective_value: Decimal
    solver_name: str
    solver_version: str
    iterations: int
    convergence_status: str  # e.g., "OPTIMAL", "INFEASIBLE"
    
    @property
    def result_hash(self) -> str:
        return CanonicalSerializer.hash(self)
